# Generated by Django 4.2.30 on 2026-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['book__title', 'id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, help_text='e.g. 1st, 2nd, Revised', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='acquired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, help_text='ISBN-10 or ISBN-13 (hyphens optional)', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='books_book_publica_75adf4_idx'),
        ),
    ]
