# Generated by Django 4.2.30 on 2026-07-16 07:25

from django.db import migrations, models


def assign_codes(apps, schema_editor):
    from books.utils import assign_author_code, assign_publisher_code
    Author = apps.get_model('books', 'Author')
    Publisher = apps.get_model('books', 'Publisher')

    for publisher in Publisher.objects.all():
        if not publisher.code:
            publisher.code = assign_publisher_code(publisher)
            publisher.save(update_fields=['code'])

    for author in Author.objects.all():
        if not author.code:
            author.code = assign_author_code(author.name)
            author.save(update_fields=['code'])


def remove_codes(apps, schema_editor):
    Author = apps.get_model('books', 'Author')
    Publisher = apps.get_model('books', 'Publisher')
    Author.objects.update(code='')
    Publisher.objects.update(code='')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Library-assigned unique 2-char code (letter + number) used in the book code.', max_length=4),
        ),
        migrations.AddField(
            model_name='publisher',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Library-assigned unique letter code for the publisher (used in the book code).', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(blank=True, db_index=True, help_text='Library verification code printed on the book to avoid manual entry.', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='year_purchased',
            field=models.PositiveIntegerField(blank=True, help_text='Year the library acquired/purchased the book (used in the book code).', null=True),
        ),
        migrations.RunPython(assign_codes, remove_codes),
        migrations.AlterField(
            model_name='author',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Library-assigned unique 2-char code (letter + number) used in the book code.', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Library-assigned unique letter code for the publisher (used in the book code).', max_length=4, unique=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_code'], name='books_book_book_co_f5a19a_idx'),
        ),
    ]
