# Generated by Django 4.2.30 on 2026-07-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowtransaction',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrowtransaction',
            index=models.Index(fields=['issue_date'], name='transaction_issue_d_e74bfc_idx'),
        ),
    ]
