# Generated by Django 4.2.30 on 2026-07-14 07:00

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(default=transactions.models.generate_receipt_number, max_length=40, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_record', to='transactions.payment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
