# Generated by Django 4.2.30 on 2026-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_return_issues',
            field=models.BooleanField(default=False, help_text='Flag for members with a tendency of not returning books. Flagged members are limited to a maximum of 10 active borrows.'),
        ),
    ]
